name: all-caches
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show environment variables
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.m2
            ~/.jeka/cache
            ~/.gradle/cache
            ./jeka-work
            ./gradle
          key: ${{ runner.os }}-all-caches

      - name: Prefetch dependencies
        run: |
          ./mvnw dependency:resolve
          ./jeka depTree --duration
          ./gradlew test clean

      - name: Maven build jar
        run: ./mvnw clean package
      - name: Jeka build jar
        run: ./jeka pack --clean --duration
      - name: Gradle build jar
        run: ./gradlew clean build -PdisableNative

      - name: Maven JVM Docker
        run: ./mvnw clean spring-boot:build-image
      - name: Jeka JVM Docker
        run: "./jeka test docker: build --clean --duration"
      - name: Gradle JVM Docker
        run: ./gradlew clean bootBuildImage -PdisableNative

      - name: Maven native Docker
        run: ./mvnw clean -Pnative spring-boot:build-image
      - name: Jeka native Docker
        run: "./jeka test docker: buildNative --clean --duration"
      - name: Gradle native Docker
        run: ./gradlew clean clean bootBuildImage

      - name: Maven native exec
        run: ./mvnw -Pnative native:compile
      - name: Jeka native exec
        run: "./jeka native: compile --duration"
      - name: Gradle native exec
        run: ./gradlew nativeCompile

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.m2
            ~/.jeka/cache
            ~/.gradle/cache
            ./jeka-work
            ./gradle
          key: ${{ runner.os }}-all-caches
