name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Maven clean package
        run: ./mvnw clean package
      - name: Jeka pack
        run: ./jeka --clean pack
      - name: Gradle clean build
        run: ./gradlew clean build -PdisableNative

      - name: Maven native exec
        run: ./mvnw -Pnative native:compile
      - name: Jeka native exec
        run: "./jeka native: compile"
      - name: Gradle native exec
        run: ./gradlew nativeCompile