name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Maven build jar
        run: ./mvnw clean package
      - name: Jeka build jar
        run: ./jeka pack --clean --duration
      - name: Gradle build jar
        run: ./gradlew clean build -PdisableNative

      - name: clean cache
        run : clean-caches.sh

      - name: Maven JVM Docker
        run: ./mvnw clean spring-boot:build-image
      - name: Jeka JVM Docker
        run: "test docker: build --clean --duration"
      - name: Gradle JVM Docker
        run: clean bootBuildImage -PdisableNative

      - name: clean cache
        run: clean-caches.sh

      - name: Maven native Docker
        run: clean -Pnative spring-boot:build-image
      - name: Jeka native Docker
        run: "test docker: buildNative --clean --duration"
      - name: Gradle native Docker
        run: clean clean bootBuildImage

      - name: clean cache
        run: clean-caches.sh

      - name: Maven native exec
        run: ./mvnw -Pnative native:compile
      - name: Jeka native exec
        run: "./jeka native: compile --duration"
      - name: Gradle native exec
        run: ./gradlew nativeCompile
